#!/usr/bin/env bash

set -e

# load common functions
. "$PIMONCLI_WORKDIR/common"

# load config 
#load_config

# =====================
cli_help_list() {
  echo "
Command: list
Usage: 
  list pimonitor systemd services
Options:
  svc --> list systemd services that ship with rbpi_monitor
"
  exit 1
}

# no argument
[ ! -n "$1" ] && cli_help_list
# unsupported argument

# case stmt
cli_log "PiMonitor: List $1"
# service|svc
echo "
Raspberry Health Monitor Systemd Services:
    - temp_monitor.service --> records Pi temp. (C) every five minutes

"

