#!/usr/bin/env bash

set -e

# load common functions
. "$PIMONCLI_WORKDIR/common"

# load config 
load_config

# =======================
cli_help_configsvc() {
  echo "
Command: svcconfig
Usage: 
  configure systemd service by name
Options:
  monitor_temp --> setup service to measure pi temperature
"
  exit 1
}

# =======================
svc_config() {
    
    # variables
    local svc_name=$1
    local svc_script=$2
    
    DATA_DIR="$PIMONAPP_WORKDIR/app/static/data"
    ERROR_DIR="$PIMONCLI_WORKDIR/error"
    
    mkdir -p $DATA_DIR
    mkdir -p $ERROR_DIR

    svc_script_path="$PIMONAPP_WORKDIR/system_setup/$svc_script.sh"

    # check if service is already configured and running
    svc_status=$(systemctl is-enabled $svc_script)
    if [ "$svc_status" = "enabled" ]; then
    	echo "service: $svc_script is already enabled"
	    exit 0
    elif [ "$svc_status" = "*Failed to get unit file state*" ]; then
    	echo "service: $svc_script not created"
	    exit 0
    else
    	echo "service: $svc_script, start enable proc"
    fi

    # svc template 
    SVC_TEMPLATE="[Unit]
    \nDescription=${svc_name}
    \n[Service]
    \nExecStart=${svc_script_path} ${DATA_DIR} ${ERROR_DIR}
    \nRestart=always
    \n[Install]
    \nWantedBy=multi-user.target
    "
    # chmod .sh script 
    chmod +x $svc_script_path
    
    # write service file 
    sudo echo -e $SVC_TEMPLATE > "/etc/systemd/system/${svc_script}.service"

    # enable svc file 
    sudo systemctl enable "${svc_script}.service"
    
    # start svc 
    sudo systemctl start "${svc_script}.service"
 
    echo "Started Service: ${svc_script}"
}

case "$1" in
  monitor_temp)
    echo "Start Config"
    svc_config "RbpiHealth_Temp" "monitor_temp"
    echo "end config"
    ;;
  *)
    cli_help_configsvc
    ;;
esac
