#!/usr/bin/env bash

set -e

# load common functions
. "$PIMONCLI_WORKDIR/common"

# =======================
cli_help_svcstop() {
  echo "
Command: svcstop
Usage: 
  stop systemd service by name
Options:
    - temp_monitor
  
"
  exit 1
}

# =======================
svc_stop() {
    
    local svc_script=$1
    # check if service is already configured and running
    svc_status=$(systemctl is-enabled $svc_script)
    if [ "$svc_status" = "*Failed to get unit file state*" ]; then
    	echo "service: $svc_script not created"
	    exit 0
    else
    	echo "service: $svc_script, start enable proc"
    fi

    # stop service 
    sudo systemctl stop "${svc_script}"
    # delete service 
    sudo systemctl disable "${svc_script}"
    # rm sym links 
    sudo rm "/etc/systemd/system/${svc_script}.service"
    #sudo rm "/usr/lib/systemd/system/${svc_script}.service"
    sudo systemctl daemon-reload
    
    echo "${svc_script} service removed"
}

case "$1" in
  monitor_temp)
    svc_stop "monitor_temp"
    ;;
  *)
    cli_help_svcstop
    ;;
esac
