#!/usr/bin/env bash

# enables the errexit option
set -e

# Temp --> set working directory
export PIMONCLI_WORKDIR=$(cd $(dirname $0) && pwd)

# load common functions
. "$PIMONCLI_WORKDIR/common"

# ========================
cli_help() {
  cli_name=${0##*/}
  echo "
$cli_name
PiMonitor CLI
Version: $(cat $PIMONCLI_WORKDIR/VERSION)
https://github.com/...
Usage: $cli_name [command]
Commands:
  list    List System Monitor Systemd Services/Status
  *       Help
"
  exit 1
}

# load config 
load_config

# exec command
case "$1" in
  list)
    "$PIMONCLI_WORKDIR/commands/list" "$2" | tee -ia "$PIMONCLI_WORKDIR/logs/list_${2}.log"
    ;;
  svcconfig)
    "$PIMONCLI_WORKDIR/commands/svcconfig" "$2" | tee -ia "$PIMONCLI_WORKDIR/logs/svcconfig_${2}.log"
    ;;
  *)
    cli_help
    ;;
esac
