#!/usr/bin/env bash

set -e
export PIMONCLI_WORKDIR=$(cd $(dirname $0) && pwd)
# shellcheck source=common
. "$PIMONCLI_WORKDIR/common"


cli_help() {
  cli_name=${0##*/}
  echo "
$cli_name
PiMonitor CLI
Version: $(cat $PIMONCLI_WORKDIR/VERSION)
https://github.com/...
Usage: $cli_name [command]
Commands:
  list    List System Monitor Systemd Services/Status
  *       Help
"
  exit 1
}

cli_log "Exporting config ..."
[ ! -f "$PIMONCLI_WORKDIR/config" ] \
  && echo "ERROR: No $PIMONCLI_WORKDIR/config file found. " \
  && echo "cp $PIMONCLI_WORKDIR/config.template $PIMONCLI_WORKDIR/config and adjust." \
  && exit 1

export $(cat "$PIMONCLI_WORKDIR/config" | xargs)

case "$1" in
  list|l)
    "$PIMONCLI_WORKDIR/commands/list" | tee -ia "$PIMONCLI_WORKDIR/logs/list_${2}.log"
    ;;
  *)
    cli_help
    ;;
esac
